spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlite:db/sqlite.db
    driver-class-name: org.sqlite.JDBC
  session:
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379
  web:
    resources:
      static-locations[0]: "file:src/main/resources/static/"
      static-locations[1]: "classpath:/static/"
